### ISSUE TITLE
Parsed form data ends up containing a huge (mostly empty) array

### ISSUE THREAD

**Issue by rob-c-baker** [jalik/js-form-parser#4]
Given a **single** form element like:

```html
<input name="contactNumbers[blocks][864536][fields][number]" type="text" value="[val]">
```

The parsed data ends up like:

```
{
    ...
    contactNumbers: {
        blocks: <Array with 864537 elements>
    }
    ...
}
```

In the above example, the `contactNumbers.blocks` array with a length of `864537` - almost all values are `null`. The array index `864536` contains the correctly parsed object: `fields.number` with a value in this case of `"[val]"`.

When this object is converted to JSON with `JSON.stringify()` for submission to the server, it ends up at approximately 4.3Mb.

Using version 2.0.5.

**Comment by jalik** [comment]
Hello @rob-baker-ar, thank you for filling this issue.
This is the normal behavior of Javascript, not of the library.
For example, try this in a JS console:
```js
const list = [];
list[100] = "hundred";
console.log(JSON.stringify(list));
```
If you insert something in an array at a specified index, it will automatically fills the array with missing previous indexes using undefined, which is replaced by null when transforming to JSON.

I would recommend to change the way you structure your form, because I am pretty sure you don't display 864 537 elements in it.
I propose you two solutions, that involve not using an array :

1. Prefixing the number with something : `contactNumbers[blocks][row_864536][fields][number]`, which will outputs this
```json
{"contactNumbers":{"blocks":{"row_864536":{"fields":{"number":"[val]"}}}}}
```

2. I could also improve to library to support explicit string index by using quotes (single ' or double ") `contactNumbers[blocks]["864536"][fields][number]`:
```json
{"contactNumbers":{"blocks":{"864536":{"fields":{"number":"[val]"}}}}}
```

In both cases, you'll have to rework your code to handle it differently, using an array in your case is not recommended as you saw it.

**Comment by jalik** [comment]
@rob-baker-ar the version v2.0.6 adds support for quoting numbers as object attribute, see https://github.com/jalik/js-form-parser#using-numbers-as-object-attribute-since-v206.

**Comment by rob-c-baker** [comment]
Hi @jalik, many thanks for this.

I was aware this is the behaviour of JavaScript - I was hoping to be able to cast the index to a string. The backend language framework in this case is not JavaScript and does not have an issue with arbitrary integer based array indexes.

So, it seems number 2 is the perfect solution for me in this case - thank you for making that change. I will swap out my implementation for that option.
